const translations = {
  ru: {
    'meta.title': 'Auralith — микроскоп времени',
    privacy: 'Работает в вашем браузере · аудио остаётся на устройстве · мы ничего не получаем · вычисления выполняются локально',
    'language.name': 'русский', 'language.switch': 'Сменить язык', 'language.code': 'RU',
    'section.source': 'Источник', 'section.transform': 'Трансформация', 'section.result': 'Прослушивание и экспорт',
    'empty.title': 'Каждый звук — целый мир.', 'empty.description': 'Выберите запись, чтобы увидеть её и выделить фрагмент.',
    'processing.summary': 'Растяжение времени · Высота тона · Разворот',
    'result.initial': 'Выберите звук, чтобы начать исследование.',
    'footer.microscope': 'МИКРОСКОП ВРЕМЕНИ', 'footer.local': 'LOCAL / WAV', 'footer.copyright': '© 2026 Кирилл Томилов',
    'status.starting': 'Запуск…', 'status.ready': 'Готово к работе', 'status.decoding': 'Декодирование аудио…', 'status.loaded': 'Источник загружен',
    'source.choose': 'Выбрать аудиофайл', 'source.limit': 'До 256 МБ · моно / стерео', 'source.decoding': 'Декодирование: {{name}}…',
    'source.mono': 'Моно · 1 канал', 'source.stereo': 'Стерео · 2 канала',
    'wave.form': 'Форма волны', 'wave.zoom': 'Масштаб', 'wave.scroll': 'Прокрутка', 'wave.aria': 'Форма волны. Для точного выделения используйте поля начала и конца ниже.',
    'wave.hint': 'Тяните границы или выделение целиком. Щёлкните и потяните вне выделения, чтобы выбрать новый фрагмент.',
    'wave.start': 'Начало', 'wave.end': 'Конец', 'wave.min': 'мин', 'wave.sec': 'сек', 'wave.ms': 'мс', 'wave.sourcePlay': '▶ Исходный фрагмент', 'wave.sourceStop': '■ Остановить исходник',
    'wave.fragment': 'Фрагмент: {{value}} с', 'wave.fragmentMs': 'Фрагмент: {{value}} мс · {{samples}} отсч.', 'wave.fragmentMsOne': 'Фрагмент: {{value}} мс · {{samples}} отсч.', 'wave.mono': 'MONO',
    'spectrogram.calculating': 'Расчёт спектрограммы…', 'spectrogram.title': 'Спектрограмма · логарифмическая шкала', 'spectrogram.aria': 'Спектрограмма с общим выделением; точное время задаётся полями ниже.',
    'spectrogram.hint': 'FFT 2048 · {{width}} временных срезов', 'spectrogram.overview': ' · обзор с пониженной детализацией, короткие события могут быть пропущены',
    'processing.duration': 'Длительность результата, с', 'processing.stretch': 'Растяжение, ×', 'processing.pitch': 'Высота тона, полутоны', 'processing.reverse': 'Развернуть источник',
    'processing.note.initial': 'Загрузите звук. Pitch не зависит от длительности.', 'processing.note.base': 'Лимит — 1 час. Pitch независим от времени.',
    'processing.note.long': 'Длинный результат: экспорт может занять несколько минут. ', 'processing.note.reverse': 'Reverse включён: источник разворачивается перед растяжением. ',
    'processing.error.longSelection': 'Выделение длиннее 1 часа. Сократите его до 3600 секунд или меньше на графике либо в полях начала и конца.',
    'processing.error.fix': 'Исправьте параметры и время выделения.', 'processing.error.agreement': 'Длительность и stretch должны быть согласованы.',
    'result.preview': 'Предпросмотр', 'result.export': 'Экспорт WAV', 'result.cancel': 'Отменить', 'result.progress': 'Обработка', 'result.note.changed': 'Параметры изменены. Нажмите «Предпросмотр» для нового прослушивания.',
    'result.note.previewShort': 'Черновое прослушивание · FFT 2048. Экспорт будет рассчитан отдельно с полным качеством.', 'result.note.previewLong': 'Черновое прослушивание: первые 20 секунд результата. Экспорт рассчитает всю длительность с полным качеством.',
    'result.play': '▶ Пуск', 'result.pause': 'Ⅱ Пауза', 'result.stop': '■ Стоп', 'result.loop': 'Зациклить',
    'status.previewPreparing': 'Подготовка предпросмотра…', 'status.previewReady': 'Предпросмотр готов', 'status.cancelled': 'Обработка отменена', 'status.exportCancelled': 'Экспорт отменён',
    'export.choose': 'Выбор файла…', 'export.processing': 'Экспорт: обработка аудио…', 'export.saving': 'Сохранение WAV…', 'export.download': 'Скачивание начато: {{name}} · {{size}} МБ', 'export.saved': 'WAV сохранён: {{name}} · {{size}} МБ',
    'error.empty': 'Файл пуст. Выберите аудиозапись.', 'error.tooLarge': 'Файл больше 256 МБ. Выберите более короткую запись.', 'error.format': 'Поддерживаются WAV, MP3, OGG и M4A.', 'error.decode': 'Не удалось декодировать файл. Он повреждён или его кодек не поддерживается браузером. Попробуйте WAV.',
    'error.sampleRate': 'Поддерживается sample rate от 8000 до 192000 Hz.', 'error.waveform': 'Не удалось построить waveform.', 'error.spectrogram': 'Не удалось рассчитать спектрограмму. Waveform остаётся доступным.',
    'error.selection': 'Начало должно быть раньше конца, а диапазон — внутри файла. На графике сохранено последнее корректное выделение.', 'error.selectionPlay': 'Исправьте время выделения перед прослушиванием.', 'error.noSource': 'Загрузите звук.',
    'error.workerPreview': 'Ошибка worker. Возможно, недостаточно памяти. Попробуйте меньший фрагмент.', 'error.workerExport': 'Ошибка экспортного worker. Возможно, недостаточно памяти.', 'error.export': 'Не удалось экспортировать WAV: {{message}}. Проверьте свободное место и попробуйте меньшую длительность.',
    'error.exportLimit': 'Для WAV больше 128 МБ нужен браузер с сохранением напрямую на диск (Chrome/Edge). Уменьшите длительность или откройте приложение в поддерживаемом браузере.', 'error.exportSize': 'Размер WAV не совпал с ожидаемым. Экспорт прерван.', 'error.playback': 'Не удалось воспроизвести: {{message}}',
    'error.sourceInvalid': 'Нужен непустой моно- или стереоисточник.', 'error.bounds': 'Некорректные границы фрагмента.', 'error.samples': 'Выделите хотя бы один отсчёт.', 'error.parameters': 'Некорректное выделение.', 'error.duration': 'Результат должен быть не короче фрагмента и не длиннее 3600 секунд.', 'error.pitch': 'Высота тона должна быть от −24 до +24 полутонов.'
  },
  en: {
    'meta.title': 'Auralith — time microscope', privacy: 'Runs in your browser · audio stays on your device · we receive nothing · all processing is local', 'language.name': 'English', 'language.switch': 'Change language', 'language.code': 'EN',
    'section.source': 'Source', 'section.transform': 'Transformation', 'section.result': 'Listen and export', 'empty.title': 'Every sound is a world.', 'empty.description': 'Choose a recording to see it and select a fragment.', 'processing.summary': 'Time stretch · Pitch · Reverse', 'result.initial': 'Choose a sound to begin exploring.', 'footer.microscope': 'TIME MICROSCOPE', 'footer.local': 'LOCAL / WAV', 'footer.copyright': '© 2026 Kirill Tomilov',
    'status.starting': 'Starting…', 'status.ready': 'Ready', 'status.decoding': 'Decoding audio…', 'status.loaded': 'Source loaded', 'source.choose': 'Choose audio file', 'source.limit': 'Up to 256 MB · mono / stereo', 'source.decoding': 'Decoding: {{name}}…', 'source.mono': 'Mono · 1 channel', 'source.stereo': 'Stereo · 2 channels',
    'wave.form': 'Waveform', 'wave.zoom': 'Zoom', 'wave.scroll': 'Scroll', 'wave.aria': 'Waveform. Use the start and end fields below for precise selection.', 'wave.hint': 'Drag a boundary or the whole selection. Click and drag outside it to choose a new fragment.', 'wave.start': 'Start', 'wave.end': 'End', 'wave.min': 'min', 'wave.sec': 'sec', 'wave.ms': 'ms', 'wave.sourcePlay': '▶ Play source fragment', 'wave.sourceStop': '■ Stop source', 'wave.fragment': 'Fragment: {{value}} s', 'wave.fragmentMs': 'Fragment: {{value}} ms · {{samples}} samples', 'wave.fragmentMsOne': 'Fragment: {{value}} ms · {{samples}} sample', 'wave.mono': 'MONO',
    'spectrogram.calculating': 'Calculating spectrogram…', 'spectrogram.title': 'Spectrogram · logarithmic scale', 'spectrogram.aria': 'Spectrogram with shared selection; set exact time in the fields below.', 'spectrogram.hint': 'FFT 2048 · {{width}} time slices', 'spectrogram.overview': ' · reduced-detail overview; short events may be missed',
    'processing.duration': 'Result duration, s', 'processing.stretch': 'Stretch, ×', 'processing.pitch': 'Pitch, semitones', 'processing.reverse': 'Reverse source', 'processing.note.initial': 'Load a sound. Pitch is independent of duration.', 'processing.note.base': 'Limit — 1 hour. Pitch is independent of time.', 'processing.note.long': 'Long result: export may take several minutes. ', 'processing.note.reverse': 'Reverse enabled: source is reversed before stretching. ', 'processing.error.longSelection': 'The selection is longer than 1 hour. Shorten it to 3600 seconds or less on the graph or in the start and end fields.', 'processing.error.fix': 'Fix the parameters and selection time.', 'processing.error.agreement': 'Duration and stretch must agree.',
    'result.preview': 'Preview', 'result.export': 'Export WAV', 'result.cancel': 'Cancel', 'result.progress': 'Processing', 'result.note.changed': 'Parameters changed. Press Preview for a new listen.', 'result.note.previewShort': 'Draft Preview · FFT 2048. Export will be rendered separately at full quality.', 'result.note.previewLong': 'Draft Preview: first 20 seconds of the result. Export will render the full duration at full quality.', 'result.play': '▶ Play', 'result.pause': 'Ⅱ Pause', 'result.stop': '■ Stop', 'result.loop': 'Loop', 'status.previewPreparing': 'Preparing preview…', 'status.previewReady': 'Preview ready', 'status.cancelled': 'Processing cancelled', 'status.exportCancelled': 'Export cancelled',
    'export.choose': 'Choose file…', 'export.processing': 'Export: processing audio…', 'export.saving': 'Saving WAV…', 'export.download': 'Download started: {{name}} · {{size}} MB', 'export.saved': 'WAV saved: {{name}} · {{size}} MB', 'error.empty': 'The file is empty. Choose an audio recording.', 'error.tooLarge': 'The file is larger than 256 MB. Choose a shorter recording.', 'error.format': 'Supported formats: WAV, MP3, OGG and M4A.', 'error.decode': 'Could not decode the file. It may be damaged or use an unsupported codec. Try WAV.', 'error.sampleRate': 'Sample rate must be between 8000 and 192000 Hz.', 'error.waveform': 'Could not build the waveform.', 'error.spectrogram': 'Could not calculate the spectrogram. The waveform is still available.', 'error.selection': 'Start must be before end, and the range must be inside the file. The last valid selection remains on the graph.', 'error.selectionPlay': 'Fix the selection time before listening.', 'error.noSource': 'Load a sound.', 'error.workerPreview': 'Worker error. There may not be enough memory. Try a smaller fragment.', 'error.workerExport': 'Export worker error. There may not be enough memory.', 'error.export': 'Could not export WAV: {{message}}. Check free space and try a shorter duration.', 'error.exportLimit': 'WAV files over 128 MB require a browser that can save directly to disk (Chrome/Edge). Reduce the duration or use a supported browser.', 'error.exportSize': 'The WAV size did not match the expected size. Export stopped.', 'error.playback': 'Could not play: {{message}}', 'error.sourceInvalid': 'A non-empty mono or stereo source is required.', 'error.bounds': 'Invalid fragment boundaries.', 'error.samples': 'Select at least one sample.', 'error.parameters': 'Invalid selection.', 'error.duration': 'The result must be at least as long as the fragment and no longer than 3600 seconds.', 'error.pitch': 'Pitch must be between −24 and +24 semitones.'
  },
  sr: {
    'meta.title': 'Auralith — mikroskop vremena', privacy: 'Radi u vašem pregledaču · audio ostaje na vašem uređaju · ništa ne primamo · obrada se obavlja lokalno', 'language.name': 'srpski', 'language.switch': 'Promeni jezik', 'language.code': 'SR',
    'section.source': 'Izvor', 'section.transform': 'Transformacija', 'section.result': 'Preslušavanje i izvoz', 'empty.title': 'Svaki zvuk je svet za sebe.', 'empty.description': 'Izaberite snimak da biste ga videli i označili fragment.', 'processing.summary': 'Vremensko rastezanje · Visina tona · Obrni', 'result.initial': 'Izaberite zvuk da biste počeli istraživanje.', 'footer.microscope': 'MIKROSKOP VREMENA', 'footer.local': 'LOKALNO / WAV', 'footer.copyright': '© 2026 Kirill Tomilov',
    'status.starting': 'Pokretanje…', 'status.ready': 'Spremno', 'status.decoding': 'Dekodiranje zvuka…', 'status.loaded': 'Izvor je učitan', 'source.choose': 'Izaberi audio-fajl', 'source.limit': 'Do 256 MB · mono / stereo', 'source.decoding': 'Dekodiranje: {{name}}…', 'source.mono': 'Mono · 1 kanal', 'source.stereo': 'Stereo · 2 kanala',
    'wave.form': 'Talasni oblik', 'wave.zoom': 'Uvećanje', 'wave.scroll': 'Pomeri', 'wave.aria': 'Talasni oblik. Za precizno označavanje koristite polja za početak i kraj ispod.', 'wave.hint': 'Pomerite granicu ili celo označeno područje. Kliknite i prevucite van njega da izaberete novi fragment.', 'wave.start': 'Početak', 'wave.end': 'Kraj', 'wave.min': 'min', 'wave.sec': 'sek', 'wave.ms': 'ms', 'wave.sourcePlay': '▶ Pusti izvorni fragment', 'wave.sourceStop': '■ Zaustavi izvor', 'wave.fragment': 'Fragment: {{value}} s', 'wave.fragmentMs': 'Fragment: {{value}} ms · {{samples}} uzoraka', 'wave.fragmentMsOne': 'Fragment: {{value}} ms · {{samples}} uzorak', 'wave.mono': 'MONO',
    'spectrogram.calculating': 'Računanje spektrograma…', 'spectrogram.title': 'Spektrogram · logaritamska skala', 'spectrogram.aria': 'Spektrogram sa zajedničkim označavanjem; tačno vreme se zadaje poljima ispod.', 'spectrogram.hint': 'FFT 2048 · {{width}} vremenskih isečaka', 'spectrogram.overview': ' · pregled sa smanjenim detaljima; kratki događaji mogu biti propušteni',
    'processing.duration': 'Trajanje rezultata, s', 'processing.stretch': 'Rastezanje, ×', 'processing.pitch': 'Pitch, polutonovi', 'processing.reverse': 'Obrni izvor', 'processing.note.initial': 'Učitajte zvuk. Pitch ne zavisi od trajanja.', 'processing.note.base': 'Ograničenje — 1 sat. Pitch ne zavisi od vremena.', 'processing.note.long': 'Dug rezultat: izvoz može trajati nekoliko minuta. ', 'processing.note.reverse': 'Obrtanje je uključeno: izvor se obrće pre rastezanja. ', 'processing.error.longSelection': 'Označeni deo je duži od 1 sata. Skraćujte ga na 3600 sekundi ili manje na grafikonu ili u poljima za početak i kraj.', 'processing.error.fix': 'Ispravite parametre i vreme označenog dela.', 'processing.error.agreement': 'Trajanje i rastezanje moraju biti usklađeni.',
    'result.preview': 'Pregled', 'result.export': 'Izvezi WAV', 'result.cancel': 'Otkaži', 'result.progress': 'Obrada', 'result.note.changed': 'Parametri su promenjeni. Pritisnite Pregled za novo preslušavanje.', 'result.note.previewShort': 'Probni pregled · FFT 2048. Izvoz će biti posebno obrađen punim kvalitetom.', 'result.note.previewLong': 'Probni pregled: prvih 20 sekundi rezultata. Izvoz će obraditi celo trajanje punim kvalitetom.', 'result.play': '▶ Pusti', 'result.pause': 'Ⅱ Pauza', 'result.stop': '■ Zaustavi', 'result.loop': 'Petlja', 'status.previewPreparing': 'Priprema pregleda…', 'status.previewReady': 'Pregled je spreman', 'status.cancelled': 'Obrada je otkazana', 'status.exportCancelled': 'Izvoz je otkazan',
    'export.choose': 'Izaberi fajl…', 'export.processing': 'Izvoz: obrada zvuka…', 'export.saving': 'Čuvanje WAV-a…', 'export.download': 'Preuzimanje je počelo: {{name}} · {{size}} MB', 'export.saved': 'WAV je sačuvan: {{name}} · {{size}} MB', 'error.empty': 'Fajl je prazan. Izaberite audio-snimak.', 'error.tooLarge': 'Fajl je veći od 256 MB. Izaberite kraći snimak.', 'error.format': 'Podržani formati: WAV, MP3, OGG i M4A.', 'error.decode': 'Fajl nije moguće dekodirati. Možda je oštećen ili koristi nepodržan kodek. Probajte WAV.', 'error.sampleRate': 'Sample rate mora biti između 8000 i 192000 Hz.', 'error.waveform': 'Talasni oblik nije moguće napraviti.', 'error.spectrogram': 'Spektrogram nije moguće izračunati. Talasni oblik je i dalje dostupan.', 'error.selection': 'Početak mora biti pre kraja, a opseg mora biti unutar fajla. Poslednji ispravan izbor ostaje na grafikonu.', 'error.selectionPlay': 'Ispravite vreme označenog dela pre preslušavanja.', 'error.noSource': 'Učitajte zvuk.', 'error.workerPreview': 'Greška radnika. Možda nema dovoljno memorije. Probajte manji fragment.', 'error.workerExport': 'Greška radnika za izvoz. Možda nema dovoljno memorije.', 'error.export': 'WAV nije moguće izvesti: {{message}}. Proverite slobodan prostor i probajte kraće trajanje.', 'error.exportLimit': 'Za WAV veći od 128 MB potreban je pregledač koji može direktno da sačuva fajl na disk (Chrome/Edge). Smanjite trajanje ili koristite podržani pregledač.', 'error.exportSize': 'Veličina WAV-a nije odgovarala očekivanoj. Izvoz je zaustavljen.', 'error.playback': 'Nije moguće pustiti zvuk: {{message}}', 'error.sourceInvalid': 'Potreban je neprazan mono ili stereo izvor.', 'error.bounds': 'Neispravne granice fragmenta.', 'error.samples': 'Izaberite bar jedan uzorak.', 'error.parameters': 'Neispravan izbor.', 'error.duration': 'Rezultat mora biti dug najmanje koliko i fragment, a najviše 3600 sekundi.', 'error.pitch': 'Pitch mora biti između −24 i +24 polutonova.'
  }
};

Object.assign(translations.ru, {
  'source.limit': 'До 256 МБ · моно / стерео', 'source.mono': 'Моно · 1 канал', 'source.stereo': 'Стерео · 2 канала',
  'processing.summary': 'Растяжение времени · Высота тона · Разворот', 'processing.pitch': 'Высота тона, полутоны', 'processing.reverse': 'Развернуть источник',
  'processing.note.initial': 'Загрузите звук. Высота тона не зависит от длительности.', 'processing.note.base': 'Лимит — 1 час. Высота тона не зависит от времени.', 'processing.note.reverse': 'Разворот включён: источник разворачивается перед растяжением. ',
  'result.preview': 'Предпросмотр', 'result.export': 'Экспорт WAV', 'result.note.changed': 'Параметры изменены. Нажмите «Предпросмотр» для нового прослушивания.', 'result.note.previewShort': 'Черновое прослушивание · FFT 2048. Экспорт будет рассчитан отдельно с полным качеством.', 'result.note.previewLong': 'Черновое прослушивание: первые 20 секунд результата. Экспорт рассчитает всю длительность с полным качеством.', 'result.play': '▶ Пуск', 'result.pause': 'Ⅱ Пауза', 'result.stop': '■ Стоп', 'result.loop': 'Зациклить',
  'status.previewPreparing': 'Подготовка предпросмотра…', 'status.previewReady': 'Предпросмотр готов',
  'error.sampleRate': 'Поддерживается частота дискретизации от 8000 до 192000 Гц.', 'error.waveform': 'Не удалось построить форму волны.', 'error.spectrogram': 'Не удалось рассчитать спектрограмму. Форма волны остаётся доступной.', 'error.workerPreview': 'Ошибка фоновой обработки. Возможно, недостаточно памяти. Попробуйте меньший фрагмент.', 'error.workerExport': 'Ошибка фоновой обработки экспорта. Возможно, недостаточно памяти.', 'error.sourceInvalid': 'Нужен непустой моно- или стереоисточник.', 'error.pitch': 'Высота тона должна быть от −24 до +24 полутонов.', 'wave.mono': 'МОНО'
});

Object.assign(translations.ru, {
  'wave.sourcePlay': '▶ 1×', 'wave.sourcePause': 'Ⅱ 1×', 'wave.help': 'Подсказка по управлению', 'wave.helpTitle': 'Управление графиками', 'wave.helpClose': 'Закрыть',
  'wave.middleDrag': 'средняя кнопка + перетаскивание', 'wave.dragPlayhead': 'перетащить синюю линию',
  'wave.help.zoom': 'Масштаб вокруг курсора', 'wave.help.scroll': 'Прокрутка по времени', 'wave.help.fastScroll': 'Быстрая прокрутка', 'wave.help.pan': 'Перемещение вида', 'wave.help.fit': 'Показать весь файл', 'wave.help.fitSelection': 'Вписать фрагмент', 'wave.help.play': 'Пуск / пауза последнего режима', 'wave.help.seek': 'Перемотка',
  'result.playSlow': '▶ {{value}}×', 'result.pauseSlow': 'Ⅱ {{value}}×', 'result.preparing': 'Подготовка…', 'result.readyIn': '{{percent}}% · примерно {{seconds}} с',
  'result.note.changed': 'Параметры изменены. Предпросмотр обновляется автоматически.', 'result.note.cancelled': 'Автоматический предпросмотр отменён. Измените параметр, чтобы запустить его снова.'
});
Object.assign(translations.en, {
  'wave.sourcePlay': '▶ 1×', 'wave.sourcePause': 'Ⅱ 1×', 'wave.help': 'Navigation help', 'wave.helpTitle': 'Graph controls', 'wave.helpClose': 'Close',
  'wave.middleDrag': 'middle button + drag', 'wave.dragPlayhead': 'drag the blue line',
  'wave.help.zoom': 'Zoom around pointer', 'wave.help.scroll': 'Scroll through time', 'wave.help.fastScroll': 'Fast scroll', 'wave.help.pan': 'Pan view', 'wave.help.fit': 'Fit entire file', 'wave.help.fitSelection': 'Fit fragment', 'wave.help.play': 'Play / pause last mode', 'wave.help.seek': 'Seek',
  'result.playSlow': '▶ {{value}}×', 'result.pauseSlow': 'Ⅱ {{value}}×', 'result.preparing': 'Preparing…', 'result.readyIn': '{{percent}}% · about {{seconds}} s',
  'result.note.changed': 'Parameters changed. Preview is updating automatically.', 'result.note.cancelled': 'Automatic preview cancelled. Change a parameter to start it again.'
});
Object.assign(translations.sr, {
  'wave.sourcePlay': '▶ 1×', 'wave.sourcePause': 'Ⅱ 1×', 'wave.help': 'Pomoć za upravljanje', 'wave.helpTitle': 'Kontrole grafikona', 'wave.helpClose': 'Zatvori',
  'wave.middleDrag': 'srednji taster + prevlačenje', 'wave.dragPlayhead': 'prevucite plavu liniju',
  'wave.help.zoom': 'Uvećanje oko pokazivača', 'wave.help.scroll': 'Pomeranje kroz vreme', 'wave.help.fastScroll': 'Brzo pomeranje', 'wave.help.pan': 'Pomeranje prikaza', 'wave.help.fit': 'Prikaži ceo fajl', 'wave.help.fitSelection': 'Uklopi fragment', 'wave.help.play': 'Pusti / pauziraj poslednji režim', 'wave.help.seek': 'Premotavanje',
  'result.playSlow': '▶ {{value}}×', 'result.pauseSlow': 'Ⅱ {{value}}×', 'result.preparing': 'Priprema…', 'result.readyIn': '{{percent}}% · približno {{seconds}} s',
  'result.note.changed': 'Parametri su promenjeni. Pregled se automatski osvežava.', 'result.note.cancelled': 'Automatski pregled je otkazan. Promenite parametar da biste ga ponovo pokrenuli.'
});

let locale = 'en';
const languageOrder = ['en', 'sr', 'ru'];

export function t(key, values = {}) {
  let text = translations[locale][key] ?? translations.ru[key] ?? key;
  return Object.entries(values).reduce((result, [name, value]) => result.replaceAll(`{{${name}}}`, String(value)), text);
}

export function translateError(message) {
  if (message === 'Нужен непустой mono или stereo источник.') return t('error.sourceInvalid');
  const exact = {
    'Файл пуст. Выберите аудиозапись.': 'error.empty', 'Файл больше 256 МБ. Выберите более короткую запись.': 'error.tooLarge', 'Поддерживаются WAV, MP3, OGG и M4A.': 'error.format', 'Поддерживается sample rate от 8000 до 192000 Hz.': 'error.sampleRate', 'Не удалось построить waveform.': 'error.waveform', 'Не удалось рассчитать спектрограмму. Waveform остаётся доступным.': 'error.spectrogram', 'Некорректные границы фрагмента.': 'error.bounds', 'Выделите хотя бы один отсчёт.': 'error.samples', 'Некорректное выделение.': 'error.parameters', 'Результат должен быть не короче фрагмента и не длиннее 3600 секунд.': 'error.duration', 'Pitch должен быть от −24 до +24 semitones.': 'error.pitch'
  };
  return exact[message] ? t(exact[message]) : message;
}

export function initI18n() {
  const toggle = document.querySelector('#language-toggle');
  const apply = () => {
    document.documentElement.lang = locale;
    document.title = t('meta.title');
    document.querySelectorAll('[data-i18n]').forEach(element => { element.textContent = t(element.dataset.i18n); });
    toggle.textContent = t('language.code');
    toggle.setAttribute('aria-label', `${t('language.switch')}: ${t('language.name')}`);
    document.dispatchEvent(new CustomEvent('languagechange', { detail: locale }));
  };
  toggle.addEventListener('click', () => { locale = languageOrder[(languageOrder.indexOf(locale) + 1) % languageOrder.length]; apply(); });
  apply();
}
